### ISSUE TITLE
Understanding UI components blog post

### ISSUE THREAD

**Issue by KasMA1990** [lucamug/elm-2022-a-year-in-review#2]
Hey, I posted the "Understanding UI Components in Elm" blog post on June 22nd, though the post was later moved to a new URL. It's now present here: https://www.crowdstrike.com/blog/tech-center/understanding-ui-components-in-elm/

**Comment by lucamug** [comment]
Thank you, I fixed the date

**Comment by lucamug** [comment]
Thank you, I fixed the date
