### ISSUE TITLE
Nethys Search - A search app for Pathfinder 2E

### ISSUE THREAD

**Issue by galdiuz** [lucamug/elm-2022-a-year-in-review#5]
I wrote a search app for the tabletop RPG Pathfinder 2nd Edition that I call Nethys Search ([repo available here](https://github.com/galdiuz/nethys-search)). It was initially released as a standalone site on the [12th of February](https://www.reddit.com/r/Pathfinder2e/comments/sqwpro/introducing_nethys_search_a_search_engine_for/), and was later integrated to the main system reference document website for the game on the [27th of July](https://www.reddit.com/r/Pathfinder2e/comments/w97ryi/archives_of_nethys_pf2e_dark_archive_pathfinder/). You can see the app in action here: https://2e.aonprd.com/Search.aspx

**Comment by lucamug** [comment]
Thank you, added
